# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-07 03:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('weather', models.BooleanField(default=True)),
                ('date_time', models.BooleanField(default=True)),
                ('quote', models.BooleanField(default=False)),
                ('user_text', models.TextField(default=b'')),
                ('location', models.TextField(default=b'Visakhapatnam, Andhra Pradesh, India')),
                ('timezone', models.TextField(default=b'5.30')),
                ('alarm', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
